export interface XfadeTransitionItem {
  id: string
  name: string
  description: string
}

export const ALL_XFADE_TRANSITIONS: XfadeTransitionItem[] = [
  { id: 'fade', name: 'Fade', description: 'Crossfade between images' },
  { id: 'wipeleft', name: 'Wipe Left', description: 'Wipe to the left' },
  { id: 'wiperight', name: 'Wipe Right', description: 'Wipe to the right' },
  { id: 'wipeup', name: 'Wipe Up', description: 'Wipe upwards' },
  { id: 'wipedown', name: 'Wipe Down', description: 'Wipe downwards' },
  { id: 'slideleft', name: 'Slide Left', description: 'Slide to the left' },
  { id: 'slideright', name: 'Slide Right', description: 'Slide to the right' },
  { id: 'slideup', name: 'Slide Up', description: 'Slide upwards' },
  { id: 'slidedown', name: 'Slide Down', description: 'Slide downwards' },
  { id: 'circlecrop', name: 'Circle Crop', description: 'Circle shape crop' },
  { id: 'rectcrop', name: 'Rect Crop', description: 'Rectangle shape crop' },
  { id: 'distance', name: 'Distance', description: 'Distance transition effect' },
  { id: 'fadeblack', name: 'Fade Black', description: 'Fade through black' },
  { id: 'fadewhite', name: 'Fade White', description: 'Fade through white' },
  { id: 'radial', name: 'Radial', description: 'Radial sweep effect' },
  { id: 'smoothleft', name: 'Smooth Left', description: 'Smooth slide to the left' },
  { id: 'smoothright', name: 'Smooth Right', description: 'Smooth slide to the right' },
  { id: 'smoothup', name: 'Smooth Up', description: 'Smooth slide upwards' },
  { id: 'smoothdown', name: 'Smooth Down', description: 'Smooth slide downwards' },
  { id: 'circleopen', name: 'Circle Open', description: 'Open circular mask' },
  { id: 'circleclose', name: 'Circle Close', description: 'Close circular mask' },
  { id: 'vertopen', name: 'Vert Open', description: 'Open vertically' },
  { id: 'vertclose', name: 'Vert Close', description: 'Close vertically' },
  { id: 'horzopen', name: 'Horz Open', description: 'Open horizontally' },
  { id: 'horzclose', name: 'Horz Close', description: 'Close horizontally' },
  { id: 'dissolve', name: 'Dissolve', description: 'Dissolve pixels' },
  { id: 'pixelize', name: 'Pixelize', description: 'Pixelation effect' },
  { id: 'diagtl', name: 'Diag TL', description: 'Diagonal from top-left' },
  { id: 'diagtr', name: 'Diag TR', description: 'Diagonal from top-right' },
  { id: 'diagbl', name: 'Diag BL', description: 'Diagonal from bottom-left' },
  { id: 'diagbr', name: 'Diag BR', description: 'Diagonal from bottom-right' },
  { id: 'hlslice', name: 'HL Slice', description: 'Horizontal left slice' },
  { id: 'hrslice', name: 'HR Slice', description: 'Horizontal right slice' },
  { id: 'vuslice', name: 'VU Slice', description: 'Vertical upward slice' },
  { id: 'vdslice', name: 'VD Slice', description: 'Vertical downward slice' },
  { id: 'hblur', name: 'HBlur', description: 'Horizontal blur transition' },
  { id: 'fadegrays', name: 'Fade Grays', description: 'Fade through grayscale' },
  { id: 'wipetl', name: 'Wipe TL', description: 'Wipe from top-left' },
  { id: 'wipetr', name: 'Wipe TR', description: 'Wipe from top-right' },
  { id: 'wipebl', name: 'Wipe BL', description: 'Wipe from bottom-left' },
  { id: 'wipebr', name: 'Wipe BR', description: 'Wipe from bottom-right' },
  { id: 'squeezeh', name: 'Squeeze H', description: 'Horizontal squeeze' },
  { id: 'squeezev', name: 'Squeeze V', description: 'Vertical squeeze' },
  { id: 'zoomin', name: 'Zoom In', description: 'Zoom in transition' },
  { id: 'fadefast', name: 'Fade Fast', description: 'Fast fade transition' },
  { id: 'fadeslow', name: 'Fade Slow', description: 'Slow fade transition' },
  { id: 'hlwind', name: 'HL Wind', description: 'Horizontal left wind effect' },
  { id: 'hrwind', name: 'HR Wind', description: 'Horizontal right wind effect' },
  { id: 'vuwind', name: 'VU Wind', description: 'Vertical upward wind effect' },
  { id: 'vdwind', name: 'VD Wind', description: 'Vertical downward wind effect' },
  { id: 'coverleft', name: 'Cover Left', description: 'Cover to the left' },
  { id: 'coverright', name: 'Cover Right', description: 'Cover to the right' },
  { id: 'coverup', name: 'Cover Up', description: 'Cover upwards' },
  { id: 'coverdown', name: 'Cover Down', description: 'Cover downwards' },
  { id: 'revealleft', name: 'Reveal Left', description: 'Reveal to the left' },
  { id: 'revealright', name: 'Reveal Right', description: 'Reveal to the right' },
  { id: 'revealup', name: 'Reveal Up', description: 'Reveal upwards' },
  { id: 'revealdown', name: 'Reveal Down', description: 'Reveal downwards' }
]
